### PR TITLE
pt-BR

### PR DESCRIPTION
**Pull request by LucasLeandroBR**
Translate extension for Portuguese ( Brazil )

### CODE REVIEW

**Comment by KyrneDev** [comment]
I've added some more localizations, do you mind adding them?

Also the file name should be pt.yml

**Comment by LucasLeandroBR** [comment]
pt = Portuguese ( Portugal )

**Comment by KyrneDev** [comment]
Alright, then it should be pt-BR.yml. Please still update to have the newest translations.

**Comment by LucasLeandroBR** [comment]
I create a extension for translate all plugins for portuguese, right

**Comment by KyrneDev** [comment]
Huh? I just need you to rename the file to add .yml to the end and add more translations for this as I updated the extension.

**Comment by KyrneDev** [comment]
Just checking to see if you got that message

**Pull request closed without merging**
